[Jellyfin]
name = "Jellyfin"
description = "Jellyfin is a free and open-source media server and suite of multimedia applications designed to organize, manage, and share digital media files to networked devices."
port = 8096

[AriaNG]
name = "Aria2 and WebGUI"
description = "aria2 is a lightweight multi-protocol & multi-source command-line download utility.It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces."
port = 9090

[Kavita]
name = "Kavita Reader"
description = "Lighting fast with a slick design, Kavita is a rocket fueled self-hosted digital library which supports a vast array of file formats. Install to start reading and share your server with your friends."
port = 8084
